//! `cargo xtask schema`: regenerate the JSON Schemas generated from the code
//! and checked in under `docs/schema/`, or with `--check`, fail when one is
//! out of date.
//!
//! Each schema is generated by a test in the crate that owns its types. The
//! test compares the checked-in file with what the build generates, and with
//! `LEVIATH_WRITE_SCHEMAS` set it writes the file first. This command runs
//! those tests, so there is one generator: the file a person regenerates is
//! the file `cargo test` (and so CI) holds the build to.

use anyhow::{Context, Result};

/// What `cargo xtask schema` does.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SchemaMode {
    /// Rewrite every generated schema from this build.
    Write,
    /// Fail when a checked-in schema differs from what this build generates.
    Check,
}

impl SchemaMode {
    /// `[]` writes; `["--check"]` checks.
    pub fn parse(args: &[String]) -> Result<Self> {
        match args {
            [] => Ok(Self::Write),
            [flag] if flag == "--check" => Ok(Self::Check),
            _ => anyhow::bail!("usage: cargo xtask schema [--check]"),
        }
    }
}

/// The tests that generate the schemas, as `(package, test)`, and the files
/// each writes under `docs/schema/`.
pub const GENERATORS: &[(&str, &str, &[&str])] = &[
    (
        "leviath-runtime",
        "runfile::tests::the_published_schemas_match_this_build",
        &["spawn-request.schema.json", "run-file.schema.json"],
    ),
    (
        "leviath-blueprint",
        "file::schema_tests::the_published_blueprint_schema_matches_this_build",
        &["blueprint.schema.json"],
    ),
];

/// The `cargo` arguments that run one generator test, and nothing else.
pub fn test_args<'a>(package: &'a str, test: &'a str) -> Vec<&'a str> {
    vec!["test", "-p", package, "--lib", "--", "--exact", test]
}

/// Whether a `cargo test` run's output says exactly one test ran and passed.
/// A filter that matches nothing passes with none, which must not read as a
/// schema that is up to date.
pub fn ran_one(stdout: &str) -> bool {
    stdout.contains("test result: ok. 1 passed;")
}

/// Run every generator, writing the files in [`SchemaMode::Write`]. Fails
/// naming the packages whose schema is out of date, or whose test did not
/// run.
pub fn run(mode: SchemaMode) -> Result<()> {
    let mut failed = Vec::new();
    for (package, test, files) in GENERATORS {
        let mut cargo = std::process::Command::new("cargo");
        cargo.args(test_args(package, test));
        match mode {
            SchemaMode::Write => cargo.env("LEVIATH_WRITE_SCHEMAS", "1"),
            SchemaMode::Check => cargo.env_remove("LEVIATH_WRITE_SCHEMAS"),
        };
        let out = cargo
            .output()
            .context("spawning cargo - is cargo installed in PATH?")?;
        let stdout = String::from_utf8_lossy(&out.stdout);
        print!("{stdout}");
        eprint!("{}", String::from_utf8_lossy(&out.stderr));
        match out.status.success() && ran_one(&stdout) {
            true => println!("[schema] {package}: {}", files.join(", ")),
            false => failed.push(*package),
        }
    }
    if !failed.is_empty() {
        anyhow::bail!(
            "[schema] out of date or not generated: {}. Run `cargo xtask schema` and commit docs/schema/.",
            failed.join(", ")
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn args(items: &[&str]) -> Vec<String> {
        items.iter().map(|s| (*s).to_owned()).collect()
    }

    #[test]
    fn no_flag_writes_and_check_checks() {
        assert_eq!(SchemaMode::parse(&[]).unwrap(), SchemaMode::Write);
        assert_eq!(
            SchemaMode::parse(&args(&["--check"])).unwrap(),
            SchemaMode::Check
        );
        assert!(SchemaMode::parse(&args(&["--write"])).is_err());
        assert!(SchemaMode::parse(&args(&["--check", "x"])).is_err());
    }

    /// Only a run of exactly one passing test counts.
    #[test]
    fn only_one_passing_test_counts() {
        assert!(ran_one("test result: ok. 1 passed; 0 failed"));
        assert!(!ran_one("test result: ok. 0 passed; 0 failed"));
        assert!(!ran_one("test result: FAILED. 0 passed; 1 failed"));
    }

    /// Each generator runs exactly one test, in its own package.
    #[test]
    fn a_generator_runs_only_its_own_test() {
        assert_eq!(
            test_args("leviath-blueprint", "schema_tests::x"),
            [
                "test",
                "-p",
                "leviath-blueprint",
                "--lib",
                "--",
                "--exact",
                "schema_tests::x"
            ]
        );
    }

    /// Every Rust source file under `dir`, read.
    fn sources(dir: &std::path::Path) -> Vec<String> {
        std::fs::read_dir(dir)
            .expect("a source directory")
            .map(|entry| entry.expect("an entry").path())
            .flat_map(|path| match path.is_dir() {
                true => sources(&path),
                false => vec![std::fs::read_to_string(&path).unwrap_or_default()],
            })
            .collect()
    }

    /// Every generator names a test that exists in its package's source, and
    /// every schema it says it writes is checked in.
    #[test]
    fn every_generator_names_a_real_test_and_real_files() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("xtask/ has a parent");
        for (package, test, files) in GENERATORS {
            let name = test.rsplit("::").next().expect("a test name");
            let defined = sources(&root.join("crates").join(package).join("src"))
                .iter()
                .any(|source| source.contains(&format!("fn {name}()")));
            assert!(defined, "{test}");
            for schema in *files {
                assert!(root.join("docs/schema").join(schema).is_file(), "{schema}");
            }
        }
    }
}
