flowchart LR
    ingest(ingest)
    analyze{{analyze}}
    script{{script}}
    report(report)
    summary(summary)
    ingest --> analyze
    analyze --> script
    analyze --> report
    script --> script
    script --> analyze
    report --> summary
    classDef entry stroke-width:3px
    class ingest entry
