flowchart TD
    research(research)
    outline{{outline}}
    draft(draft)
    edit{{edit}}
    proofread{{proofread}}
    summary(summary)
    research --> outline
    outline --> draft
    outline --> outline
    outline --> summary
    outline --> research
    draft --> edit
    edit --> draft
    edit --> proofread
    proofread --> summary
    proofread --> edit
    classDef entry stroke-width:3px
    class research entry
